# Generated by Django 5.1.3 on 2024-11-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='answer',
            field=models.TextField(default=6, verbose_name='Ответ'),
            preserve_default=False,
        ),
    ]
