# Generated by Django 5.1.3 on 2024-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_homework_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_score',
            field=models.IntegerField(default=2, verbose_name='Макс оценка'),
            preserve_default=False,
        ),
    ]
