# Generated by Django 5.1.3 on 2024-11-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_testtries_test_testtries_score_testtries_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtries',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_tries', to='app.testquestion', verbose_name='Вопрос'),
        ),
    ]
