# Generated by Django 5.1.3 on 2024-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_testtries_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='max_score',
            field=models.IntegerField(default=2, verbose_name='Максимальная оценка'),
        ),
        migrations.AddField(
            model_name='testtries',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='score',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='testtries',
            name='score',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='grade',
            field=models.FloatField(blank=True, help_text='Оценка доступна только для завершённых курсов', null=True, verbose_name='Оценка'),
        ),
    ]
